project:
  type: manuscript
  output-dir: docs
  #when rendering, comment this out. when hosting to webpage, then run it

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: false



